# Generated by Django 2.2.2 on 2019-06-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('url', models.URLField()),
                ('created', models.DateTimeField()),
                ('changed', models.DateTimeField()),
                ('published', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('live', 'LIVE'), ('started', 'STARTED'), ('ended', 'ENDED'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED')], default='draft', max_length=9)),
                ('organizer_name', models.CharField(max_length=250, null=True)),
                ('category_name', models.CharField(max_length=250, null=True)),
                ('event_sales_status', models.CharField(choices=[('on_sale', 'ON_SALE'), ('not_yet_on_sale', 'NOT_YET_ON_SALE'), ('sales_ended', 'SALES_ENDED'), ('sold_out', 'SOLD_OUT'), ('unavailable', 'UNAVAILABLE')], default='unavailable', max_length=15)),
                ('currency', models.CharField(max_length=3)),
                ('minimum_ticket_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('maximum_ticket_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('local_created_at', models.DateTimeField(auto_now_add=True)),
                ('local_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
